onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - puppeteer

patchedDependencies:
  '@lexical/html': patches/@lexical__html.patch
  htmr@1.0.2: patches/htmr@1.0.2.patch

ignoredBuiltDependencies:
  - esbuild
  - sharp
