name: Deploy to OCI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      env:
        NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}
      with:
        # ssh host
        host: ${{ secrets.OCI_VM_IP }}
        username: ${{ secrets.OCI_VM_USERNAME }}
        key: ${{ secrets.OCI_VM_SSH }}
        envs: NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA
        # execute commands
        script: |
          cd ~/matheditor
          git fetch
          git reset --hard origin/master
          npm ci
          npx prisma migrate deploy
          npm run build
          pm2 reload "matheditor"